/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin")
	id("org.beryx.runtime")
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

javafx {
    version = "24.0.2"
    modules("javafx.controls", "javafx.fxml", "javafx.base")
}


dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
	testImplementation("org.mockito:mockito-junit-jupiter:5.11.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    
    implementation("net.bytebuddy:byte-buddy-agent:1.15.1")
    
     // Основной стартер для работы с БД (Hibernate + Spring Data JPA)
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework:spring-jcl:6.1.6") 
    
    // База данных H2
    runtimeOnly("com.h2database:h2")
    
    // Дополнительно: если нужен веб-интерфейс H2 Console или REST
    implementation("org.springframework.boot:spring-boot-starter-web:4.0.6")
    implementation("jakarta.servlet:jakarta.servlet-api:6.0.0")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.alex.app.SpaceInfo"
//    mainModule = "spaceInfo"
}
version = "1.0.3"

tasks.withType<JavaExec>{
	systemProperty("java.awt.headless", "false")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    enabled = false
}
tasks.named<Jar>("jar") {
    enabled = true
}

runtime {
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))
    
    // Поскольку проект немодульный, jlink не знает, какие модули JDK нужны.
    // Для Spring Boot + JPA + H2 + JavaFX этот список обязателен:
    modules.set(listOf(
        "java.base",            // Базовый модуль Java (всегда обязателен)
        "java.sql",             // Работа с БД (JDBC, H2)
        "java.desktop",         // Рендеринг и работа JavaFX / AWT
        "java.instrument",      // ByteBuddy, Spring AOP, агенты
        "java.logging",         // Логирование Spring
        "jdk.unsupported",      // Низкоуровневая рефлексия (Jackson, СGLIB)
        "jdk.jfr",              // Метрики и профилирование Spring Boot
        "java.scripting",       // Скрипты и динамический контекст Spring
        "java.xml",             // Конфигурации и парсинг XML
        "java.naming",          // JNDI контексты и DataSource
        "java.compiler",        // Динамическая компиляция прокси-классов
        "java.transaction.xa",   // Транзакции Hibernate / JPA
        "java.management"
    ))

    imageDir.set(layout.buildDirectory.dir("runtime-image"))

    launcher {
        noConsole = true
        jvmArgs = listOf("-Djava.awt.headless=false")
    }

    // Аналог вашего блока jlink.jpackage для сборки приложения без инсталлятора
    jpackage {
        imageName  = "SpaceInfo"
        outputDir = layout.buildDirectory.dir("compilatedApp").get().asFile.absolutePath
        skipInstaller = true
        
        // Если понадобится иконка, раскомментируйте:
        // imageOptions.set(listOf(
        //     "--icon", 
        //     layout.projectDirectory.file("src/main/resources/AppIcon.ico").asFile.absolutePath
        // ))
    }
}
